# Generated by Django 4.1.5 on 2023-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regionSelection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.CharField(help_text='Users name', max_length=200)),
                ('lastName', models.CharField(help_text='Users lastname', max_length=200)),
                ('meliCode', models.IntegerField(help_text='Users meli code(unique) ', primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200)),
                ('phoneNumber1', models.IntegerField(help_text='Users phone number(required)')),
                ('phoneNumber2', models.IntegerField(blank=True, help_text='Users phone number(not required) for social purposes')),
                ('homeNumber1', models.IntegerField(blank=True, help_text='Users home number')),
                ('locationLat', models.IntegerField(help_text='Users location latitude')),
                ('locationLong', models.IntegerField(help_text='Users location long')),
                ('region', models.ManyToManyField(to='regionSelection.region')),
            ],
        ),
    ]
