# Generated by Django 4.1.5 on 2023-01-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerUser', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='locationLat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locationLong',
        ),
    ]
