# Generated by Django 4.1.5 on 2023-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionName', models.CharField(help_text='The region name', max_length=200)),
                ('city', models.CharField(choices=[('Tehran', 'Tehran')], help_text='regions city', max_length=200)),
                ('country', models.CharField(choices=[('Iran', 'Iran')], help_text='Regions country', max_length=200)),
            ],
        ),
    ]
