# Generated by Django 4.1.5 on 2023-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regionSelection', '0002_alter_region_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city',
            field=models.CharField(choices=[('Tehran', 'تهران'), ('kerman', 'کرمان')], help_text='regions city', max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(choices=[('Iran', 'ایران')], help_text='Regions country', max_length=200),
        ),
    ]
